name: Maven Build and Deploy

on:
  push:
    branches:
      - development
      - uat
      - master
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Validate & Compile
        run: mvn -s settings.xml -B clean -DskipTests compile

      - name: Run Tests
        run: mvn -s settings.xml -B clean test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/uat' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Modify POM
        run: |
          sed -i -e "s/<groupId>com.mycompany<\/groupId>/<groupId>${{ vars.businessGroupId }}<\/groupId>/" pom.xml
          sed -i -e "s/<version>1.0.0-SNAPSHOT<\/version>/<version>1.0.0-${{ github.run_number }}-${{ github.ref_name }}<\/version>/" pom.xml
          head -n 10 pom.xml

      - name: Deploy
        run: |
          mvn -s settings.xml -B clean -DskipTests deploy
          if [[ "${GITHUB_REF##*/}" == "development" ]]; then
            mvn -s settings.xml -B clean -DskipTests deploy \
              -DmuleDeploy -Denvironment="DEV" -Dmule.env="development" -Dmule.key="${{ secrets.nonprod_key }}" \
              -Dcloudhub.application.name=${{ vars.apiname }}-dev \
              -Danypoint.platform.client_id="${{ vars.ANYPOINT_DEV_ID }}" \
              -Danypoint.platform.client_secret="${{ secrets.ANYPOINT_DEV_SECRET }}"
          elif [[ "${GITHUB_REF##*/}" == "uat" ]]; then
            mvn -s settings.xml -B clean -DskipTests deploy \
              -DmuleDeploy -Denvironment="QA" -Dmule.env="testing" -Dmule.key="${{ secrets.nonprod_key }}" \
              -Dcloudhub.application.name=${{ vars.apiname }}-testing \
              -Danypoint.platform.client_id="${{ vars.ANYPOINT_TEST_ID }}" \
              -Danypoint.platform.client_secret="${{ secrets.ANYPOINT_TEST_SECRET }}"
          elif [[ "${GITHUB_REF##*/}" == "master" ]]; then
            head -n 50 pom.xml
            mvn -s settings.xml -B clean -DskipTests deploy \
              -DmuleDeploy -Denvironment="PROD" -Dmule.env="production" -Dmule.key="${{ secrets.prod_key }}" \
              -Dcloudhub.application.name=${{ vars.apiname }} \
              -Danypoint.platform.client_id="${{ vars.ANYPOINT_PROD_ID }}" \
              -Danypoint.platform.client_secret="${{ secrets.ANYPOINT_PROD_SECRET }}"
